### PR TITLE
GitHub Action to build Android release

### PR DESCRIPTION
**Pull request by gardner**
Not sure if you want to incorporate this yet but I hope it helps to get some CI going. It takes about 10-15 minutes per build which could probably be improved with some caching.

### CODE REVIEW

**Comment by danemadsen** [comment]
lgtm

**Comment by danemadsen** [comment]
Any ideas why the action is failing? I setup the key how you said in the readme?

**Comment by gardner** [comment]
Just a heads up. It requires some configuration that is described in the [README](https://github.com/danemadsen/maid/blob/main/.github/workflows/README.md).

You can use a throwaway key until you are ready to publish to the Play Store. People will be able to side-load it.

It still requires a "publish on new tag". Right now it just uploads the APK as an artifact to the GitHub Actions build page. I don't think they are public unless they are explicitly published. 

I'll see if I can get "publish on new tag" working and submit a PR.

**Comment by gardner** [comment]
Maybe there was a trailing space on one of the strings added in secrets? You could try setting the values again.

You can see the values being masked with `***` in the *Create key.properties* step. So it seems like the names are correct.

```
* What went wrong:
Execution failed for task ':app:packageRelease'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > com.android.ide.common.signing.KeytoolException: Failed to read key *** from store "/home/runner/work/maid/maid/android/app/key.jks": Get Key failed: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
```

**Pull request merged**
